// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2CceZnnJrPHrWuA-6UBiWMxHpZtVsk5M',
    appId: '1:594422195001:web:ed3a5758505abac4177ee8',
    messagingSenderId: '594422195001',
    projectId: 'smart-traffic-a9d28',
    authDomain: 'smart-traffic-a9d28.firebaseapp.com',
    databaseURL: 'https://smart-traffic-a9d28-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-traffic-a9d28.appspot.com',
    measurementId: 'G-0GSD066ZEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZqIgJQnTx45OEEWc9GapZdPKDMpafe54',
    appId: '1:594422195001:android:f67c0a54a4220328177ee8',
    messagingSenderId: '594422195001',
    projectId: 'smart-traffic-a9d28',
    databaseURL: 'https://smart-traffic-a9d28-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-traffic-a9d28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo1WBS6Xnf3ZsvynCQHo8CiEi9bVSbFTM',
    appId: '1:594422195001:ios:f739b9e822c7b00b177ee8',
    messagingSenderId: '594422195001',
    projectId: 'smart-traffic-a9d28',
    databaseURL: 'https://smart-traffic-a9d28-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-traffic-a9d28.appspot.com',
    iosBundleId: 'com.sayurupriyanjana.trafficAnalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo1WBS6Xnf3ZsvynCQHo8CiEi9bVSbFTM',
    appId: '1:594422195001:ios:f739b9e822c7b00b177ee8',
    messagingSenderId: '594422195001',
    projectId: 'smart-traffic-a9d28',
    databaseURL: 'https://smart-traffic-a9d28-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-traffic-a9d28.appspot.com',
    iosBundleId: 'com.sayurupriyanjana.trafficAnalysis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2CceZnnJrPHrWuA-6UBiWMxHpZtVsk5M',
    appId: '1:594422195001:web:056da9e2b3e1f4da177ee8',
    messagingSenderId: '594422195001',
    projectId: 'smart-traffic-a9d28',
    authDomain: 'smart-traffic-a9d28.firebaseapp.com',
    databaseURL: 'https://smart-traffic-a9d28-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-traffic-a9d28.appspot.com',
    measurementId: 'G-YPV5KQMXX2',
  );
}
